// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_b2OQsRJiBUsxYiQHJljmORq2_QoWzXM',
    appId: '1:301079922827:web:39be9048784129323bec8e',
    messagingSenderId: '301079922827',
    projectId: 'fir-react-native-ed913',
    authDomain: 'fir-react-native-ed913.firebaseapp.com',
    storageBucket: 'fir-react-native-ed913.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCL2jC3fPfFwJtvJfp-EqGv8t57Kp5QcAM',
    appId: '1:301079922827:android:e668df9e83c09aee3bec8e',
    messagingSenderId: '301079922827',
    projectId: 'fir-react-native-ed913',
    storageBucket: 'fir-react-native-ed913.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3h0XePk33IVAYgaFZq5U5u2ErShuTSyY',
    appId: '1:301079922827:ios:c68e0948ae6397ee3bec8e',
    messagingSenderId: '301079922827',
    projectId: 'fir-react-native-ed913',
    storageBucket: 'fir-react-native-ed913.firebasestorage.app',
    iosBundleId: 'com.example.carbonCreditProject',
  );
}
